# Generated by Django 4.2.1 on 2023-05-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название Тура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='tour_image', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='NewsVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='tour_video', verbose_name='Видео')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_carousel_videos', to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_carousel_img', to='news.news')),
            ],
        ),
    ]
