# Generated by Django 4.2.1 on 2023-05-26 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
